export const LOGIN_USER_ONGOING = 'LOGIN_USER_ONGOING'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED'

export const REGISTER_USER_ONGOING = 'REGISTER_USER_ONGOING'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED'

export const GET_SECTOR = 'GET_SECTOR'